---
displayMode: compact
---

gantt
    dateFormat  YYYY-MM-DD
    title       xBFreE Roadmap
    
    section xBFreE Package
        Publish v1.0.0rc1 release   :milestone, 2023-07-01, 0d
        Publish stable release (v1.0.0)   :milestone, 2023-07-16, 0d
        Publish v1.1.0rc1 release   :milestone, 2023-08-01, 0d
        Publish v1.1.0 stable release   :milestone, 2023-08-16, 0d
        Publish v2.0.0rc1 release   :milestone, 2023-09-16, 0d
        Publish stable release (v2.0.0)   :milestone, 2023-10-16, 0d

    section xBFreE Development
        Develop and test   :            des1, 2023-05-01, 2023-06-30
        Fix bugs and typos    :            des2, 2023-07-01, 2023-07-15
        MMPBSA (APBS) :            des1, 2023-07-15, 2023-07-31
        Fix bugs and typos  :            des1, 2023-08-01, 2023-08-15
        LIE (D-Model)  :            des1, 2023-08-15, 2023-09-15
        Fix bugs and typos     :            des2, 2023-09-16, 2023-10-15
